In [28]:
import pandas as pd
df=pd.read_csv("covid_vaccine_statewise.csv")

In [29]:
df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df.groupby('State')['First Dose Administered'].sum()

State
Andaman and Nicobar Islands                 1.642585e+07
Andhra Pradesh                              1.232861e+09
Arunachal Pradesh                           4.900498e+07
Assam                                       5.856002e+08
Bihar                                       1.470503e+09
Chandigarh                                  4.470310e+07
Chhattisgarh                                7.960029e+08
Dadra and Nagar Haveli and Daman and Diu    3.359506e+07
Delhi                                       6.243395e+08
Goa                                         7.599137e+07
Gujarat                                     2.131646e+09
Haryana                                     7.557984e+08
Himachal Pradesh                            3.162940e+08
India                                       2.826214e+10
Jammu and Kashmir                           4.101018e+08
Jharkhand                                   6.036737e+08
Karnataka                                   1.873330e+09
Kerala                                      1.193845e+09
Ladakh                                      1.780925e+07
Lakshadweep                                 4.363655e+06
Madhya Pradesh                              1.796605e+09
Maharashtra                                 2.784364e+09
Manipur                                     6.740957e+07
Meghalaya                                   6.261597e+07
Mizoram                                     4.787308e+07
Nagaland                                    4.241077e+07
Odisha                                      1.032633e+09
Puducherry                                  4.134686e+07
Punjab                                      5.843466e+08
Rajasthan                                   2.201044e+09
Sikkim                                      3.698093e+07
Tamil Nadu                                  1.288533e+09
Telangana                                   8.803206e+08
Tripura                                     1.926897e+08
Uttar Pradesh                               2.788411e+09
Uttarakhand                                 3.631914e+08
West Bengal                                 1.796450e+09
Name: First Dose Administered, dtype: float64

In [32]:
df.groupby('State')['Second Dose Administered'].sum()

State
Andaman and Nicobar Islands                 4.118554e+06
Andhra Pradesh                              3.588176e+08
Arunachal Pradesh                           1.193232e+07
Assam                                       1.307888e+08
Bihar                                       2.707906e+08
Chandigarh                                  1.159374e+07
Chhattisgarh                                1.721204e+08
Dadra and Nagar Haveli and Daman and Diu    4.594416e+06
Delhi                                       1.882189e+08
Goa                                         1.619817e+07
Gujarat                                     6.004184e+08
Haryana                                     1.586561e+08
Himachal Pradesh                            7.383858e+07
India                                       6.759621e+09
Jammu and Kashmir                           8.595165e+07
Jharkhand                                   1.221211e+08
Karnataka                                   4.271872e+08
Kerala                                      3.640488e+08
Ladakh                                      5.453762e+06
Lakshadweep                                 1.056446e+06
Madhya Pradesh                              3.169330e+08
Maharashtra                                 7.128811e+08
Manipur                                     1.185815e+07
Meghalaya                                   1.216663e+07
Mizoram                                     9.998418e+06
Nagaland                                    9.204637e+06
Odisha                                      2.513028e+08
Puducherry                                  8.608859e+06
Punjab                                      1.211210e+08
Rajasthan                                   4.917030e+08
Sikkim                                      9.723640e+06
Tamil Nadu                                  2.906706e+08
Telangana                                   1.981529e+08
Tripura                                     6.527014e+07
Uttar Pradesh                               5.544351e+08
Uttarakhand                                 1.000850e+08
West Bengal                                 5.861469e+08
Name: Second Dose Administered, dtype: float64

In [35]:
df['Male(Individuals Vaccinated)'].sum()

7138698858.0

In [36]:
df['Female(Individuals Vaccinated)'].sum()

6321628736.0